name: Test Stdlib Modules

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/com/thorn/stdlib/**'
      - 'tests/stdlib/**'
      - '.github/workflows/test-stdlib.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/com/thorn/stdlib/**'
      - 'tests/stdlib/**'
      - '.github/workflows/test-stdlib.yml'

jobs:
  test-stdlib:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build ThornLang
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
    
    - name: Run Stdlib Tests
      run: |
        echo "Running all stdlib tests..."
        failed=0
        total=0
        
        # Find all test files in tests/stdlib/
        for test_file in tests/stdlib/*_test.thorn; do
          if [ -f "$test_file" ]; then
            total=$((total + 1))
            test_name=$(basename "$test_file" .thorn)
            echo ""
            echo "========================================"
            echo "Running $test_name..."
            echo "========================================"
            
            if java com.thorn.Thorn "$test_file"; then
              echo "✅ $test_name passed"
            else
              echo "❌ $test_name failed"
              failed=$((failed + 1))
            fi
          fi
        done
        
        echo ""
        echo "========================================"
        echo "Test Summary: $((total - failed))/$total tests passed"
        echo "========================================"
        
        if [ $failed -ne 0 ]; then
          echo "❌ $failed tests failed"
          exit 1
        else
          echo "✅ All stdlib tests passed!"
        fi